# Generated by Django 3.2.9 on 2022-01-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=222)),
                ('lastname', models.CharField(max_length=222)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=222)),
            ],
        ),
    ]
